# Generated by Django 5.2 on 2026-02-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_product_wholesale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sale_type',
            field=models.CharField(choices=[('retail', '零售'), ('wholesale', '批发')], default='retail', max_length=20, verbose_name='销售方式'),
        ),
    ]
