# Generated by Django 6.0.1 on 2026-02-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_saleitem_sale_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="member",
            name="level",
        ),
        migrations.RemoveField(
            model_name="member",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="member",
            name="user",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="member",
        ),
        migrations.RemoveField(
            model_name="membertransaction",
            name="member",
        ),
        migrations.RemoveField(
            model_name="rechargerecord",
            name="member",
        ),
        migrations.RemoveField(
            model_name="membertransaction",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="rechargerecord",
            name="operator",
        ),
        migrations.AddField(
            model_name="sale",
            name="member_id",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="会员ID"
            ),
        ),
        migrations.DeleteModel(
            name="MemberLevel",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
        migrations.DeleteModel(
            name="MemberTransaction",
        ),
        migrations.DeleteModel(
            name="RechargeRecord",
        ),
    ]
