# Generated by Django 6.0.1 on 2026-02-09 18:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_remove_member_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="仓库的唯一名称",
                        max_length=100,
                        unique=True,
                        verbose_name="仓库名称",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="仓库的唯一编码，用于程序内部标识",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.RegexValidator(
                                message="仓库编码只能包含字母、数字和下划线",
                                regex="^[a-zA-Z0-9_]+$",
                            ),
                        ],
                        verbose_name="仓库编码",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="仓库的详细地址",
                        max_length=255,
                        null=True,
                        verbose_name="地址",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="仓库的联系电话",
                        max_length=20,
                        null=True,
                        verbose_name="联系电话",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        help_text="仓库的联系人姓名",
                        max_length=50,
                        null=True,
                        verbose_name="联系人",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="控制仓库是否参与库存业务逻辑",
                        verbose_name="是否启用",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="标识系统中的默认仓库",
                        verbose_name="是否默认仓库",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="自动记录仓库的创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="自动记录仓库的最后更新时间",
                        verbose_name="更新时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "仓库",
                "verbose_name_plural": "仓库",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="inventory_w_code_2cdc02_idx"),
                    models.Index(
                        fields=["is_active"], name="inventory_w_is_acti_3ddeac_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="inventory.warehouse",
                verbose_name="仓库",
            ),
        ),
        migrations.CreateModel(
            name="WarehouseInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        help_text="当前仓库中该商品的实际库存数量",
                        verbose_name="库存数量",
                    ),
                ),
                (
                    "warning_level",
                    models.IntegerField(
                        default=10,
                        help_text="库存预警阈值，当数量低于此值时触发预警",
                        verbose_name="预警数量",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="自动记录库存记录的创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="自动记录库存的最后更新时间",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_inventories",
                        to="inventory.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventories",
                        to="inventory.warehouse",
                        verbose_name="仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "仓库库存",
                "verbose_name_plural": "仓库库存",
                "indexes": [
                    models.Index(
                        fields=["product", "warehouse"],
                        name="inventory_w_product_a897c4_idx",
                    ),
                    models.Index(
                        fields=["warehouse", "quantity"],
                        name="inventory_w_warehou_6d7607_idx",
                    ),
                ],
                "unique_together": {("product", "warehouse")},
            },
        ),
    ]
