# Generated by Django 6.0.1 on 2026-02-10 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_document_warehouse(apps, schema_editor):
    Warehouse = apps.get_model("inventory", "Warehouse")
    Sale = apps.get_model("inventory", "Sale")
    InventoryCheck = apps.get_model("inventory", "InventoryCheck")

    default_warehouse = Warehouse.objects.filter(is_default=True, is_active=True).first()
    if not default_warehouse:
        return

    Sale.objects.filter(warehouse__isnull=True).update(warehouse=default_warehouse)
    InventoryCheck.objects.filter(warehouse__isnull=True).update(warehouse=default_warehouse)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_soft_delete_sale_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorycheck",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_checks",
                to="inventory.warehouse",
                verbose_name="仓库",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="inventory.warehouse",
                verbose_name="仓库",
            ),
        ),
        migrations.RunPython(backfill_document_warehouse, noop),
        migrations.CreateModel(
            name="UserWarehouseAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="标识该用户的默认仓库",
                        verbose_name="默认仓库",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="禁用后该授权关系不参与权限判断",
                        verbose_name="是否启用",
                    ),
                ),
                (
                    "permission_bits",
                    models.PositiveIntegerField(
                        default=31,
                        help_text="按位存储仓库权限，例如查看、销售、入库、出库、盘点",
                        verbose_name="权限位",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_accesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_accesses",
                        to="inventory.warehouse",
                        verbose_name="仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户仓库授权",
                "verbose_name_plural": "用户仓库授权",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="inventory_u_user_id_a43682_idx",
                    ),
                    models.Index(
                        fields=["warehouse", "is_active"],
                        name="inventory_u_warehou_2858a3_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "warehouse"), name="uniq_user_warehouse_access"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True), ("is_default", True)),
                        fields=("user",),
                        name="uniq_active_default_warehouse_per_user",
                    ),
                ],
            },
        ),
    ]
