# Generated by Django 6.0.1 on 2026-02-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_inventorycheck_warehouse_sale_warehouse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="颜色"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="尺码"
            ),
        ),
    ]
