# Generated by Django 6.0.1 on 2026-02-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_alter_product_color_alter_product_size"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Inventory",
        ),
    ]
