# Generated by Django 6.0.1 on 2026-02-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_sale_abandoned_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="account_holder",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="挂账人"
            ),
        ),
    ]
