# Generated by Codex on 2026-02-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_product_manufacturer_to_supplier(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    Supplier = apps.get_model('inventory', 'Supplier')

    for product in Product.objects.exclude(manufacturer__isnull=True).exclude(manufacturer='').iterator():
        supplier_name = (product.manufacturer or '').strip()
        if not supplier_name:
            continue
        supplier, _ = Supplier.objects.get_or_create(
            name=supplier_name,
            defaults={'is_active': True},
        )
        if product.supplier_id != supplier.id:
            product.supplier_id = supplier.id
            product.save(update_fields=['supplier'])


def migrate_debtorder_payee_to_supplier(apps, schema_editor):
    DebtOrder = apps.get_model('inventory', 'DebtOrder')
    Supplier = apps.get_model('inventory', 'Supplier')

    fallback_supplier, _ = Supplier.objects.get_or_create(
        name='未指定供货商',
        defaults={'is_active': True},
    )

    for order in DebtOrder.objects.all().iterator():
        supplier_name = (order.payee_name or '').strip()
        if supplier_name:
            supplier, _ = Supplier.objects.get_or_create(
                name=supplier_name,
                defaults={'is_active': True},
            )
        else:
            supplier = fallback_supplier
        if order.supplier_id != supplier.id:
            order.supplier_id = supplier.id
            order.save(update_fields=['supplier'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_debtorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='products',
                to='inventory.supplier',
                verbose_name='供货商',
            ),
        ),
        migrations.RunPython(migrate_product_manufacturer_to_supplier, noop),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='debtorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='debtorder',
            name='deleted_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='debt_orders_deleted',
                to=settings.AUTH_USER_MODEL,
                verbose_name='删除人',
            ),
        ),
        migrations.AddField(
            model_name='debtorder',
            name='deleted_reason',
            field=models.TextField(blank=True, verbose_name='删除原因'),
        ),
        migrations.AddField(
            model_name='debtorder',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='debtorder',
            name='settlement_mode',
            field=models.CharField(
                choices=[
                    ('CASH_SETTLED', '现金结清'),
                    ('CREDIT_PAYABLE', '挂账应付'),
                ],
                default='CREDIT_PAYABLE',
                max_length=20,
                verbose_name='结算方式',
            ),
        ),
        migrations.AddField(
            model_name='debtorder',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='来源对象ID'),
        ),
        migrations.AddField(
            model_name='debtorder',
            name='source_type',
            field=models.CharField(
                choices=[
                    ('MANUAL', '手工创建'),
                    ('PRODUCT_CREATE', '商品建档'),
                    ('PRODUCT_IMPORT', '商品导入'),
                    ('INVENTORY_IN', '手工入库'),
                    ('INVENTORY_IMPORT', '批量入库'),
                ],
                default='MANUAL',
                max_length=30,
                verbose_name='来源类型',
            ),
        ),
        migrations.AddField(
            model_name='debtorder',
            name='supplier',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='debt_orders',
                to='inventory.supplier',
                verbose_name='供货商',
            ),
        ),
        migrations.RunPython(migrate_debtorder_payee_to_supplier, noop),
        migrations.RemoveField(
            model_name='debtorder',
            name='payee_name',
        ),
        migrations.AlterField(
            model_name='debtorder',
            name='supplier',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='debt_orders',
                to='inventory.supplier',
                verbose_name='供货商',
            ),
        ),
        migrations.AlterModelOptions(
            name='debtorder',
            options={
                'ordering': ['-created_at'],
                'verbose_name': '应付款订单',
                'verbose_name_plural': '应付款订单',
            },
        ),
    ]
