# Generated by Django 6.0.1 on 2026-03-03 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_supplier_payable_refactor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="debtorder",
            name="offset_of",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offset_entry",
                to="inventory.debtorder",
                verbose_name="冲销原应付款",
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="is_voided",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="是否作废"
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="reversal_of",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal_transaction",
                to="inventory.inventorytransaction",
                verbose_name="冲销原交易",
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="void_reason",
            field=models.TextField(blank=True, default="", verbose_name="作废原因"),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="作废时间"),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voided_inventory_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作废人",
            ),
        ),
        migrations.AlterField(
            model_name="debtorder",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("MANUAL", "手工创建"),
                    ("PRODUCT_CREATE", "商品建档"),
                    ("PRODUCT_IMPORT", "商品导入"),
                    ("INVENTORY_IN", "手工入库"),
                    ("INVENTORY_IMPORT", "批量入库"),
                    ("INVENTORY_VOID_OFFSET", "入库作废冲销"),
                ],
                default="MANUAL",
                max_length=30,
                verbose_name="来源类型",
            ),
        ),
    ]
